[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-boot-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies" }
spring-boot-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-security-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-security-oauth2-jose = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }

commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

auth0-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }

postgresql-driver = { module = "org.postgresql:postgresql", version.ref = "postgresql-driver"}

springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version = "2.8.13" }

locationtech-jts-core = { module = "org.locationtech.jts:jts-core", version.ref = "locationtech-jts" }
locationtech-jts-common = { module = "org.locationtech.jts.io:jts-io-common", version.ref = "locationtech-jts" }

jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }

hibernate-spatial = { module = "org.hibernate.orm:hibernate-spatial" }

[versions]
spring-boot = "3.5.1"
spring-dep-mgmt = "1.1.6"
mapstruct = "1.6.0"
lombok = "1.18.42"
junit = "5.11.0"
geolatte = "1.8.2"
jooq = "3.20.5"
commons-io = "2.16.1"
java-jwt = "4.4.0"
postgresql-driver = "42.7.7"
locationtech-jts = "1.20.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }


